[project]
name = "yu-playlist-client"
version = "0.2.0"
requires-python = ">=3.14"
dependencies = [
   "apsw>=3.53.3.0",
   "colorama>=0.4.6",
   "google-api-python-client>=2.177.0",
   "google-api-python-client-stubs>=1.30.0",
   "google-auth-httplib2>=0.2.0",
   "google-auth-oauthlib>=1.2.2",
   "pathvalidate>=3.3.1",
   "prompt-toolkit>=3.0.52",
   "pydantic>=2.13.4",
   "wcwidth>=0.2.13",
]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[dependency-groups]
dev = [
   "pytest>=8.4.2",
   "pytest-cov>=7.0.0",
]
